create table relogio (
       id bigint generated by default as identity,
        data_cadastro date not null,
        marca varchar(50) not null,
        status varchar(255) not null,
        primary key (id)
    )